services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - './docker:/docker-entrypoint-initdb.d'
      - db:/var/lib/postgresql/data
    networks:
      - app
      - db

#  app:
#    build: .
#    depends_on:
#      - db
#    container_name: server
#    restart: unless-stopped
#    ports:
#      - $PORT:$PORT
#    environment:
#      - DATABASE_URL=$DATABASE_URL
#    networks:
#      - app

volumes:
  db:
networks:
    app:
      driver: bridge
    db:
      driver: bridge